### ISSUE TITLE
Screamer M.2 USB-C to M.2 key A+E adapter

### ISSUE THREAD

**Issue by Mera-balou** [ufrisk/pcileech-fpga#65] opened 2020-07-12 22:18 UTC
Hi Ulf Frisk,

I already have a Screamer M.2 USB-C and a Thunderbolt adapter ([this one](https://fr.aliexpress.com/item/32867546205.html)).
I would also like to be able to connect my Screamer to a Wifi port on a laptop (M.2 key A + E).
There are a lot of different form factors and i'm afraid of being wrong. I wanted to know if you could advise me a compatible adapter between the Screamer and and the Wifi port please.

**Comment by ufrisk** [comment] 2020-07-12 22:55
There are so many different adapters around this so I'd rather not give advise so I won't give you the wrong one.

But there are plenty of a+e to standard pcie adapters out there. Maybe some to key M as well.

**Comment by Mera-balou** [comment] 2020-07-13 20:11
Yes, there are so many different adapters and formats that I get lost. 
[This one](http://www.adt.link/product/R54SF.html) seems to be suitable.

**Comment by ufrisk** [comment] 2020-07-16 11:36
I agree, it does look very nice indeed :) Maybe I shall even get one of those myself. Thanks.

**Comment by craigsblackie** [comment] 2020-07-29 15:57
I've ordered this adaptor and the Sintech. I'll see how they compare.

**Comment by craigsblackie** [comment] 2020-08-04 16:23
So, I can confirm the Sintech adaptor works perfectly. On the Dell Precision devices, I've found that the NvME port doesn't work but the Wifi a+e port does, so definitely worth investing.

**Comment by craigsblackie** [comment] 2020-08-06 13:07
I've just received the ADT-Link R54SF and it's a lot more sturdy looking than the Sintech which uses a flimsy ribbon cable. Saying that, ribbon cables are cheap so it wouldnt be too much trouble to replace if it got damaged.

**Comment by ufrisk** [comment] 2024-06-01 15:49
I'm closing this issue due to old age.

**Closed by ufrisk** 2024-06-01 15:49 UTC
Labels: question
